#!/bin/bash
version="0.1"
set -e

main ()
	{
		DIR="$( cd "$( dirname "$0" )" && pwd )"
		export DIR
		# shellcheck disable=SC1090
		source "$DIR/functions.sh"

		while [[ "$1" != "" ]]; do
			case $1 in
				-a | --add )
					add_to
					exit;;
				-r | --remove )
					remove_from
					exit;;
				-R | --read )
					read_path
					exit;;
				-v | --version )
					echo $version
					exit;;
				-h | --help )
					usage
					exit;;
				* )
					usage
					exit 1;;
			esac
		done
	}

if [[ $EUID != 0 ]]; then
	main "$@"
else
	echo ""
	echo "Cannot run this script as root or sudo, please don't..."
	exit
fi
